app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/news/urls.py
from django.urls import path

from news.views import index, alone, statistics

app_name = 'news'
urlpatterns = [
    path('alone/<int:pk>/', alone, name='alone'),
    path('statistic/', statistics, name='stat'),
    path('', index, name='index'),
]

app/news/models.py
import datetime
from random import randint

from django.db import models


class NewsModel(models.Model):
    name = models.CharField(max_length=80, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст")
    image = models.ImageField(
        blank=True,
        verbose_name="Image",
        upload_to=str(datetime.datetime.now()) + str(randint(-10000, 10000)),
    )
    tegs = models.ManyToManyField("TegsModel", related_name="tegs")
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата")
    views_new = models.IntegerField(verbose_name="Просмотры", default=0)

    class Meta:
        verbose_name_plural = "News"
        verbose_name = "News"
        ordering = ["-create_at"]

    def delete(self, *args, **kwargs):
        for i in self.additionalimage_set.all():
            i.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name


class AdditionalImage(models.Model):
    new = models.ForeignKey(NewsModel, on_delete=models.CASCADE, verbose_name="P")
    image = models.ImageField(
        upload_to=str(datetime.datetime.now()) + str(randint(-10000, 10000)),
        verbose_name="Image",
    )

    class Meta:
        verbose_name = "AddImage"


class TegsModel(models.Model):
    name = models.CharField(max_length=40, verbose_name="Название тега", unique=True)

    class Meta:
        verbose_name = "Teg"

    def __str__(self):
        return self.name

app/news/views.py
from django.shortcuts import render

from news.models import NewsModel


def index(request):
    if "teg" in request.GET:
        news = NewsModel.objects.filter(tegs__pk=request.GET["teg"]).prefetch_related(
            "tegs"
        )
    else:
        news = NewsModel.objects.prefetch_related("tegs").all()
    context = {"news": news}
    return render(request, "main/index.html", context)


def alone(request, pk):
    new = NewsModel.objects.defer("tegs").get(pk=pk)
    view = new.views_new + 1
    new.views_new = view
    new.save()
    ais = new.additionalimage_set.all()
    return render(request, "main/alone.html", {"new": new, "ais": ais})


def statistics(request):
    news_stat = NewsModel.objects.all().order_by("-views_new").defer("tegs")
    context = {"news_stat": news_stat}
    return render(request, "main/statis.html", context)

app/news/templates/basis.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>
    {% block title %}
    {% endblock title %}
        - News</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'news:index' %}">Главная</a></li>
            <li><a href="#">Поиск по тегу</a>
                <ul>
                    
                    {% for i in navbar_tegs %}
                        <li><a href="{% url 'news:index' %}?teg={{i.pk}}">{{i.name}}</a></li>
                    {% endfor %}

                </ul>
            </li>
            <li><a href="{% url 'news:stat' %}">Статистика</a></li>
        </ul>
    </nav>
    
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>

app/news/templates/main/alone.html
{% extends 'basis.html' %}
{% load thumbnail %} 

{% block title %}
    {{new.pk}}
{% endblock title %}
    
{% block content %}



<div class="single_product_img">
    <p>
        <img src="{% thumbnail new.image '300x200' crop='smart' %}" alt="cat">
    {%for i in ais %}
    <img src="{% thumbnail i.image '300x200' crop='smart' %}" alt="#" class="img-fluid">

    {%endfor%}
    </p>
    <h3>{{new.name}}</h3>
    <hr>
    <h4><textarea rows="10" cols="265" name="text">{{new.text}}</textarea></h4>
</div>
<div class="card-content">
    <hr>
    <h3>{{new.create_at}}</h3>

</div>
{% endblock content %}
    

app/news/templates/main/index.html
{% extends 'basis.html' %}
{% load thumbnail %} 
{% block title %}
    Главная
{% endblock title %}

{% block content %}
<div class="card">
    
    {% for i in news %}
    
        <div class="column ">
            <div class="card-content">
                <a href="{% url 'news:alone' pk=i.pk %}">
                    <h3>{{i.name}}</h3>
                </a>
            <h4>Теги:</h4>

                {% for teg in i.tegs.all %}
                    <h5 ><font  color="#fa8e47" face="serif">{{teg.name}}</font></h5>
                {% endfor %}

            </div>
            
            <img src="{% thumbnail i.image '300x200' crop='smart' %}" alt="cat">
            <div class="card-content">

                <h3>{{i.create_at}}</h3>

            </div>
            
        </div>
    <hr>
    {% endfor %}
{% endblock content %}
    

app/news/templates/main/statis.html
{% extends 'basis.html' %}
{% load thumbnail %} 

{% block title %}
    Statistics
{% endblock title %}

{% block content %}
<style>
    table.text  {
     width:  50%; /* Ширина таблицы */
     border-spacing: 0; /* Расстояние между ячейками */
    }
    table.text td {
     width: 50%; /* Ширина ячеек */
     vertical-align: top; /* Выравнивание по верхнему краю */
    }
    
</style>
<table class="text">
    <tr>
        <td>Заголовок</td>
        <td class="rightcol">Колличество просмотров</td>
    </tr>
</table>
<hr>
<hr>

{% for i in news_stat %}
<table class="text">
    <tr>
        <td><a href="{% url 'news:alone' pk=i.pk %}">{{i.name}}</a></td>
        <td class="rightcol">{{i.views_new}}</td>
    </tr>
</table>
<hr>
{% endfor %}
{% endblock content %}
    